name: dmman
description: dmman is a chat app, you can message, call, and more.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # packages
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.12.9
  firebase_auth: '0.11.1+7'
  google_sign_in: 4.0.2
  shimmer: 1.0.1
  gradient_app_bar: ^0.1.3
  emoji_picker: ^0.1.0
  image_picker: ^0.6.3+1
  path_provider: ^1.6.0
  image: ^2.1.19
  firebase_storage: ^3.1.1
  provider: ^4.0.3
  cached_network_image: ^2.0.0
  agora_rtc_engine: ^1.0.8
  permission_handler: 3.0.0
  hive: ^1.4.1+1
  sqflite: ^1.3.0
  intl: ^0.16.1
  flutter_svg: ^0.19.0
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # the assets
  assets:
    - assets/images/
  
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen.otf
  
    - family: Farray
      fonts:
        - asset: assets/fonts/farray.otf
    
    - family: OS
      fonts:
        - asset: assets/fonts/open_sans.ttf
    
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf

    - family: Razed_T
      fonts:
        - asset: assets/fonts/razed_t.ttf

    - family: Razed
      fonts:
        - asset: assets/fonts/razed.ttf
